server:
  port: 8080

spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/virtualpet?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: vp_user
    password: vp_pass

  server:
    error:
      include-message: always
      include-binding-errors: always
      include-stacktrace: never



  jpa:
    hibernate:
      ddl-auto: update        # solo en desarrollo
    open-in-view: false       # buena práctica en APIs
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        # format_sql: true     # (opcional) ver SQL bonito en logs

jwt:
  secret: ${JWT_SECRET}        # define JWT_SECRET como variable de entorno
  expirationMinutes: 120
