# src/main/resources/application-local.yml
logging:
  level:
    root: INFO
    cat.itacademy.virtualpet: INFO
    cat.itacademy.virtualpet.infrastructure.security: DEBUG

spring:
  # (opcional) ver SQL bonito en consola mientras desarrollas
  jpa:
    properties:
      hibernate:
        format_sql: true
  # todo lo demás (datasource, cache, etc.) hereda de application.yml

jwt:
  # clave HS256 en Base64 (32 bytes). ¡Solo para DEV!
  secret: MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=
  expirationMinutes: 120
