
logging:
  level:
    root: INFO
    cat.itacademy.virtualpet: INFO
    cat.itacademy.virtualpet.infrastructure.security: DEBUG

spring:

  jpa:
    properties:
      hibernate:
        format_sql: true

jwt:

  secret: MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=
  expirationMinutes: 120
