

logging:
  level:
    root: INFO
    cat.itacademy.virtualpet: INFO
    cat.itacademy.virtualpet.infrastructure.security: DEBUG

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/virtualpet?useSSL=false&serverTimezone=Europe/Madrid
    username: vp_user
    password: vp_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never


jwt:
  secret: MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=
  expirationMinutes: 120
