server:
  port: 8080

spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/virtualpet?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: vp_user
    password: vp_pass

  server:
    error:
      include-message: always
      include-binding-errors: always
      include-stacktrace: never

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


jwt:
  secret: ${JWT_SECRET}
  expirationMinutes: 120
