spring:
  datasource:
    url: jdbc:mysql://localhost:3306/virtualpet?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: vp_user
    password: vp_pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  profiles:
    active: local

server:
  port: 8080
